// Importamos los tipos y funciones necesarias desde Next.js y otras dependencias.
import type { Metadata } from "next";  // Tipo para definir la metadata del documento.
import { Geist, Geist_Mono } from "next/font/google";  // Funciones para cargar fuentes de Google Fonts.
import "./globals.css";  // Importación de los estilos globales del proyecto.

// Cargamos la fuente "Geist" y asignamos una variable CSS para utilizarla en el proyecto.
const geistSans = Geist({
  variable: "--font-geist-sans",  // Variable CSS para la fuente Geist.
  subsets: ["latin"],  // Subconjunto de caracteres (en este caso, latino).
});

// Cargamos la fuente "Geist Mono" y asignamos una variable CSS para utilizarla en el proyecto.
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",  // Variable CSS para la fuente Geist Mono.
  subsets: ["latin"],  // Subconjunto de caracteres (en este caso, latino).
});

// Definimos la metadata del proyecto, que se incluirá en el documento HTML.
export const metadata: Metadata = {
  title: "Create Next App",  // Título de la página web.
  description: "Generated by create next app",  // Descripción de la página.
};

// Componente `RootLayout`, que sirve como envoltorio global para todas las páginas.
// Recibe `children` como propiedad, que será el contenido de la página.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;  // Tipo para los niños (contenido) del componente.
}>) {
  return (
    // Estructura HTML básica: <html> y <body> son los contenedores principales de la página.
    <html lang="en">  {/* Establecemos el idioma del documento como inglés. */}
      {/* El <body> incluye las clases necesarias para las fuentes y estilo antialiasing. */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}  // Aplicamos las fuentes y estilo antialiased.
      >
        {/* Renderizamos el contenido dinámico dentro de la página, proporcionado por `children`. */}
        {children}
      </body>
    </html>
  );
}
